# Generated by Django 3.2.4 on 2021-08-12 17:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210807_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Product.random_file_name),
        ),
    ]
